# Change these first
owner: amsc-tech # Your GitHub organization or username, where this repository lives
repo: amskey-status # The name of this repository

sites:
  - name: Amskey
    url: https://amskey.f5.si
  - name: Media Server
    url: https://media.amsc.f5.si/amskey

status-website:
  cname: status.amskey.f5.si
  # baseUrl: /your-repo-name
  logoUrl: https://portal.amskey.f5.si/assets/logo.png
  name: Amskey Status
  introTitle: "Amskey Status"
  introMessage: Status of Amskey and related services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
